services:
  api:
    image: kirixo/libum_api:1.0.0
    depends_on:
      - database
    volumes:
      - ./backend:/app
      - ./backend/dockerbuild:/build
    networks:
      - app-network
      - db-network

  database:
    image: postgres:15
    container_name: postgres_db
    restart: always
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: kirixo
      POSTGRES_PASSWORD: 1111
      POSTGRES_DB: libumdb
    volumes:
      - ./db/libumdb_tables.sql:/docker-entrypoint-initdb.d/libumdb_tables.sql
    networks:
      - db-network

  frontend:
    image: node:16-alpine
    container_name: web_builder
    working_dir: /app
    volumes:
      - /app/node_modules
      - ./web:/app
    environment:
      - NODE_ENV=development
    command: sh -c "npm install && npm run build"
    depends_on:
      - api

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./web/dist:/usr/share/nginx/html
    depends_on:
      - api
      - frontend
    networks:
      - app-network

networks:
  app-network:
  db-network:
